---
# https://www.electronjs.org/docs/latest/tutorial/snapcraft

name: nest-desktop
title: NEST Desktop
summary: Simulate spiking neuronal networks
description: |
  Create spiking neuron models, run simulation and analyze the results.

  **Are you having issues?**

  Let us know by creating a new issue here: https://github.com/nest-desktop/nest-desktop-snap/issues
license: MIT
icon: snap/gui/nest-desktop.png
version: 4.0.5

base: core22
grade: stable # options: devel, stable
confinement: strict

# for core22
architectures:
  - build-on: [amd64]

# for core24
# platforms:
#   amd64:
#   arm64:

apps:
  nest-desktop:
    command: bin/nest-desktop-launch
    common-id: io.github.nest_desktop.nest-desktop
    desktop: usr/share/applications/nest-desktop.desktop
    environment:
      NESTML_MODULES_PATH: /tmp/nestmlmodules
    extensions: [gnome]
    plugs:
      - browser-support # use functions essential for web browsers
      - home # access non-hidden files in the home directory
      - network # enables network access
      - network-bind # operate as a network service

parts:
  bsi-trigger:
    plugin: nil
    source: https://github.com/nest-desktop/nest-desktop-snap.git

  desktop-launch:
    plugin: dump
    source: .
    stage:
      - bin
      - usr

  nest-desktop:
    plugin: nil
    build-snaps:
      - node/22/stable
    override-build: |
      yarn install; yarn app:build --linux dir
      cp -rv ./release/linux-unpacked ${CRAFT_PART_INSTALL}/nest-desktop
    source: https://github.com/nest-desktop/nest-desktop.git
    source-depth: 1
    source-branch: v4.0.5
    source-type: git
    stage-packages:
      - libnspr4
      - libnss3

  # nest-simulator:
  #   plugin: cmake
  #   cmake-parameters:
  #     - -DCMAKE_INSTALL_PREFIX:PATH=/usr
  #     # - -DCMAKE_BUILD_TYPE=Release   # Compile without debug, make it faster
  #   build-packages:
  #     - build-essential
  #     - cmake
  #     - cython3
  #     - libgsl-dev
  #     - libltdl-dev
  #     - libmpich-dev
  #     - libncurses5-dev
  #     - libopenmpi-dev
  #     - libreadline-dev
  #     - pandoc
  #     - python3-dev
  #     - python3-pip
  #     - wget
  #   override-build: |
  #     python3 -m pip install cython
  #     python3 -m pip install -r ${CRAFT_PART_SRC}/requirements_pynest.txt
  #     python3 -m pip install -r ${CRAFT_PART_SRC}/requirements_nest_server.txt
  #     craftctl default
  #     # cmake -DCMAKE_INSTALL_PREFIX:PATH=${CRAFT_PART_INSTALL} ${CRAFT_PART_SRC}
  #     # make -j $(nproc)
  #     # make install
  #   source: https://github.com/nest/nest-simulator.git
  #   source-depth: 1
  #   source-tag: v3.7
  #   source-type: git
  #   stage-packages:
  #     - libgsl-dev

  backend-tools:
    plugin: conda
    # for core22
    build-environment:
      - PATH: /root/miniconda/bin:$PATH
      - PYTHONPATH: /root/miniconda/lib/python3.10/site-packages
    # conda-miniconda-version: "py310_24.9.2-0" # https://repo.anaconda.com/miniconda/
    conda-packages:
      - flask
      - flask_cors
      - gunicorn
      - libtool
      - nest-simulator==3.8
      - nestml==8.0
      # - norse
      - numpy
      - requests
      - restrictedpython
      - werkzeug
      - --channel conda-forge
    conda-python-version: "3.10"
    stage:
      - -bin/nest-config
      - -doc
      - -extras

  backend-server:
    plugin: python
    python-packages:
      - nestml-server@git+https://github.com/babsey/nestml-server@v1.0-b8
      # - norse-server@git+https://github.com/babsey/norse-server.git
      - --no-deps
    source: https://github.com/nest-desktop/nest-desktop-snap
    source-depth: 1
    source-type: git
    stage:
      - bin/nestml-server
      - lib/python3.10/site-packages/nestml_server
