---
# https://www.electronjs.org/docs/latest/tutorial/snapcraft

name: nest-desktop
title: NEST Desktop
summary: Simulate spiking neuronal networks
description: |
  Create spiking neuron models, run simulation and analyze the results.
license: MIT
icon: snap/gui/nest-desktop.png
version: 4.2.0

source-code:
  - https://github.com/nest-desktop/nest-desktop-snap
contact:
  - spreizer@web.de
website:
  - https://nest-desktop.github.io
issues:
  - https://github.com/nest-desktop/nest-desktop-snap/issues


base: core24
grade: stable # options: devel, stable
confinement: strict

# for core22
# architectures:
#   - build-on: [amd64]

# for core24
platforms:
  amd64:
  arm64:

apps:
  nest-desktop:
    command: bin/nest-desktop-launch
    common-id: io.github.nest_desktop.nest-desktop
    desktop: usr/share/applications/nest-desktop.desktop
    # environment:
    #   NESTML_MODULES_PATH: /tmp/nestmlmodules
    #   NESTML_SERVER_TIMEOUT: 120
    extensions: [gnome]
    plugs:
      - browser-support # use functions essential for web browsers
      - home # access non-hidden files in the home directory
      - network # enables network access
      - network-bind # operate as a network service

parts:
  bsi-trigger:
    plugin: nil
    source: https://github.com/nest-desktop/nest-desktop-snap.git

  desktop-launch:
    plugin: dump
    source: .
    stage:
      - bin
      - usr

  nest-desktop:
    plugin: dump
    source: https://github.com/nest-desktop/nest-desktop-electron/releases/download/v4.2.0/nest-desktop-4.2.0.tar.gz
    override-build: |
      cp -rv . ${CRAFT_PART_INSTALL}/nest-desktop
    stage-packages:
      - libnspr4
      - libnss3

  # nest-simulator:
  #   plugin: cmake
  #   cmake-parameters:
  #     - -DCMAKE_INSTALL_PREFIX:PATH=/usr
  #     # - -DCMAKE_BUILD_TYPE=Release   # Compile without debug, make it faster
  #   build-packages:
  #     - build-essential
  #     - cmake
  #     - cython3
  #     - libgsl-dev
  #     - libltdl-dev
  #     - libmpich-dev
  #     - libncurses5-dev
  #     - libopenmpi-dev
  #     - libreadline-dev
  #     - pandoc
  #     - python3-dev
  #     - python3-pip
  #     - wget
  #   override-build: |
  #     python3 -m pip install cython
  #     python3 -m pip install -r ${CRAFT_PART_SRC}/requirements_pynest.txt
  #     python3 -m pip install -r ${CRAFT_PART_SRC}/requirements_nest_server.txt
  #     craftctl default
  #     # cmake -DCMAKE_INSTALL_PREFIX:PATH=${CRAFT_PART_INSTALL} ${CRAFT_PART_SRC}
  #     # make -j $(nproc)
  #     # make install
  #   source: https://github.com/nest/nest-simulator.git
  #   source-depth: 1
  #   source-tag: v3.7
  #   source-type: git
  #   stage-packages:
  #     - libgsl-dev

  backend-tools:
    plugin: conda
    build-environment:
      - CONDA_PLUGINS_AUTO_ACCEPT_TOS: "yes"
    # conda-miniconda-version: "latest"   # https://repo.anaconda.com/miniconda/
    conda-packages:
      - flask
      - flask-cors
      - gunicorn
      - nest-simulator==3.9
      # - nestml==8.2
      - restrictedpython
      - --channel conda-forge
    conda-python-version: "3.12"
    stage:
      - -bin/nest-config
      - -doc
      - -extras

  # backend-server:
  #   plugin: python
  #   python-packages:
  #     - nestml-server@git+https://github.com/babsey/nestml-server@v1.0
  #     # - norse-server@git+https://github.com/babsey/norse-server.git
  #     - --no-deps
  #   source: https://github.com/nest-desktop/nest-desktop-snap
  #   source-depth: 1
  #   source-type: git
  #   stage:
  #     - bin/nestml-server
  #     - lib/python3.10/site-packages/nestml_server
