---
# https://www.electronjs.org/docs/latest/tutorial/snapcraft#using-electron-installer-snap

name: nest-desktop
title: NEST Desktop
summary: A web-based GUI application for NEST Simulator.
description: |
  Create spiking neuron models, run simulation and analyze the results.

base: core22
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  bsi-trigger:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/nest-desktop/nest-desktop-snap.git

  desktop-launch:
    plugin: dump
    # prime:
    #   - bin
    source: .
    stage:
      - bin

  nest-desktop:
    plugin: dump
    build-packages:
      - bison
      - build-essential
      - clang
      - g++-multilib
      - gcc-multilib
      - gperf
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libdbus-1-dev
      - libgtk-3-dev
      - libnotify-dev
      - libnss3-dev
      - libxss1
      - libxtst-dev
      - openjdk-8-jre
      - python3-dbusmock
    build-snaps:
      - node/20/stable
    override-build: |
      craftctl default
      yarn install
      yarn app:build:deb
      dpkg -x ${CRAFT_PART_BUILD}/release/*.deb ${CRAFT_PART_INSTALL}
    source: https://github.com/nest-desktop/nest-desktop.git
    source-depth: 1
    source-branch: dev
    source-type: git
    stage:
      - -opt/nest-desktop/chrome-sandbox
      - opt/nest-desktop
      - usr/share
    stage-packages:
      - libnspr4
      - libnss3
      - libxss1

  # nest-desktop:
  #   override-build: |
  #     snapcraftctl build
  #   plugin: dump
  #   prime:
  #     - -opt/nest-desktop/chrome-sandbox    # exclude this
  #   source: https://github.com/nest-desktop/nest-desktop/releases/download/v3.2-rc2/nest-desktop_3.2.0-rc2_amd64.deb
  #   source-type: deb
  #   stage-packages:
  #     - libappindicator3-1
  #     - libasound2
  #     - libgbm-dev
  #     - libgl1
  #     - libnspr4
  #     - libnss3
  #     - libsecret-1-0
  #     - libxss1

  nest-simulator:
    conda-miniconda-version: "py39_4.12.0" # https://repo.anaconda.com/miniconda/
    conda-packages:
      - flask
      - flask_cors
      - gunicorn
      - libtool
      - nest-simulator
      - numpy
      - requests
      - restrictedpython
      - werkzeug
      - --channel conda-forge
    conda-python-version: "3.10"
    stage:
      - -bin/nest-config
      - -doc
      - -extras

  backend-server:
    plugin: python
    python-packages:
      - nestml-server@git+https://github.com/babsey/nestml-server@v1.0-b4
      # - norse-server@git+https://github.com/babsey/norse-server.git
      - --no-deps
    source: https://github.com/nest-desktop/nest-desktop-snap
    source-depth: 1
    source-type: git
    stage:
      - bin/nestml-server
      - lib/python3.10/site-packages/nestml_server
